title: Settings
data:
  site_name: 'Huy Tran - Dev Blog'
  personality: casual
  show_signup: false
  social:
    -
      id: gm1tVoeo
      name: Github
      url: 'https://github.com/huy-tran'
      icon: site/social-icons/github.svg
    -
      id: QmcMOfcu
      name: Email
      url: 'mailto:hygo.tran@gmail.com'
      icon: site/social-icons/email.svg
